### ISSUE TITLE
Can I use with ActixWeb4?

### ISSUE THREAD

**Issue by measproem** [Flowneee/tarantool-rs#1]
How to import use in ActixWeb 4 may I have sample code

**Comment by Flowneee** [comment]
NOTE: this crate is very much work in progress, not even published on crates.io, so I cannot guarantee any API compatibility or even will it compile or not. You might want to try https://github.com/zheludkovm/RustyTarantool, we use it in production currently, no problem except this library doesn't implement transaction features (begin/commit/rollback requests) or https://github.com/picodata/tarantool-module, but it is sync only.

I just updated code, so crate depend on tokio with a few features, which should allow to use it with actix runtime. So you need just create connection inside `actix_rt::main` (or any other permanently living `Arbiter`, because connection spawns background task), I believe this should be enough.

**Comment by measproem** [comment]
Thank you so much
